<div class="page-header">
  <h1>Wellcome to Yace</h1>
</div>
<p class="lead">Yace stands for Yaf lAyout Capable viEw, which is a layout capable view engine run on Yaf.<br />Yace solves some basic problems that you would enconter in your daily development, such as layout and nested view structure.<br />The following list demonstrates some basic functionalities:</p>
<div>
  <ul class="nav nav-pills nav-stacked">
    <li role="presentation"><a href="<?php echo $this->baseUri ?>index/show-layout-view-example/">Layout view</a></li>
    <li role="presentation"><a href="<?php echo $this->baseUri ?>index/show-nested-view-structure-example">Nested view structure</a></li>
    <li role="presentation"><a href="<?php echo $this->baseUri ?>index/show-switch-layout-example">Switch layout</a></li>
    <li role="presentation"><a href="<?php echo $this->baseUri ?>index/show-disabled-layout-example">Disabled layout</a></li>
  </ul>
</div>
